<a href="https://colab.research.google.com/github/anpmht/433-Mhz-fr-transmitter-and-receiver-code/blob/master/nn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
def sigmoid(x):
  return 1/(1 + np.exp(-x))

def sigmoid_derivative(x):
  return x*(1-x)

training_data = np.array([[1,1,0],
                         [1,0,1],
                         [0,1,1]])
training_output = np.array([[1,1,0]]).T

In [30]:

np.random.seed(1)

synaptic_weight = 2 * np.random.random((3,1)) - 1
print(synaptic_weight)
for iteration in range(100000):
  input_layer = training_data
  outputs = sigmoid(np.dot(input_layer,synaptic_weight))
  error = training_output - outputs
  adjustments = error * sigmoid_derivative(outputs)
  synaptic_weight += np.dot(input_layer.T, adjustments)

print('synaptic weights after training :')
print(synaptic_weight)

print('outputs after training :')
print(outputs)


[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
synaptic weights after training :
[[ 9.23285869]
 [-2.99181096]
 [-2.99249701]]
outputs after training :
[[0.99805596]
 [0.99805463]
 [0.00251164]
 [0.5       ]]
